
server:
  port: 9000
  servlet:
    context-path: /contact-manager


spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5438}/${POSTGRESQL_DB:contactManager}
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  application:
    name: contact-manager-service
  profiles:
    active: local

logging:
  level:
    root: INFO
    com:
      givaudan: DEBUG
